server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  application: #userservice的名称信息         --- eureka启动之后将注册到服务中心之中
#    name: userserver
#  cloud:
#    nacos:
#      server-addr: localhost:8848  #nacos服务地址
#      discovery:
#        cluster-name: SH #集群名称，这里SH代指杭州


mybatis:
  type-aliases-package: com.hml.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.hml: debug
  pattern:
#    dateformat: MM-dd HH:mm:ss:SSS
    name: 本地环境Local
#eureka:
#  client:
#    service-url: #eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka




