server:
  port: 10086

spring:
  application: #eureka的名称信息         --- eureka启动之后也将注册到服务中心之中
    name: eurekaserver


eureka:
  client:
    service-url: #eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
